/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in a standard project and is committed here
// so Vercel can type-check the minimal App Router base from a clean checkout.
