/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js and kept in version control so TypeScript
// can resolve Next.js types before the first local `next dev` or `next build`.
